# Generated by Django 4.2.5 on 2023-09-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice_field",
                    models.CharField(
                        choices=[
                            ("choice1", "Label Choice 1"),
                            ("choice2", "Label Choice 2"),
                            ("choice3", "Label Choice 3"),
                        ],
                        default="choice1",
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
